export const vi = {
  // App
  app_title: "MS Thumbnail Studio",
  app_subtitle: "Tạo thumbnail bằng AI",

  // Tabs (must be SHORT — no wrapping in segmented control)
  tab_title: "Title",
  tab_thumbnail: "Thumbnail",
  tab_edit: "Sửa",
  tab_gallery: "Thư viện",
  tab_watermark: "Watermark",

  // Settings
  set_title: "Cài đặt",
  set_subtitle: "API Keys & Model",
  set_keys_title: "API Keys",
  set_google_key: "Google AI API Key",
  set_google_key_ph: "AIza...",
  set_anthropic_key: "Anthropic API Key",
  set_anthropic_key_ph: "sk-ant-...",
  set_show: "Hiện",
  set_hide: "Ẩn",
  set_saved: "Đã lưu tự động",
  set_models_title: "Chọn Model",
  set_title_model: "Model cho Title Studio",
  set_text_model: "Model cho AI gợi ý",
  set_thumb_model: "Model cho Thumbnail (cố định)",
  set_thumb_model_locked: "Chỉ Gemini mới tạo được ảnh",
  set_provider_gemini: "Google Gemini",
  set_provider_anthropic: "Anthropic Claude",
  set_badge_best: "Best",
  set_badge_fast: "Fast",

  // Title Studio
  ts_title: "Title Studio",
  ts_subtitle: "Nghiên cứu & tạo title hấp dẫn",
  ts_topic: "Ý tưởng video",
  ts_topic_ph: "Mô tả ngắn gọn nội dung video... VD: tôi thua lệnh vì không dùng stop loss",
  ts_script: "Nội dung video (không bắt buộc)",
  ts_script_ph: "Paste script / kịch bản video vào đây để AI hiểu sâu nội dung và tạo title chính xác hơn...",
  ts_script_chars: (n: number) => `${n} từ`,
  ts_audience: "Đối tượng",
  ts_generate: "Tạo title",
  ts_generating: "Đang tạo...",
  ts_regenerate: "Tạo lại",
  ts_results: (n: number) => `${n} title được tạo`,
  ts_use_title: "Dùng title này",
  ts_used: "Đang dùng",
  ts_score: "Điểm",
  ts_formula: "Công thức",
  ts_score_emotion: "Cảm xúc",
  ts_score_clarity: "Rõ ràng",
  ts_score_curiosity: "Tò mò",
  ts_score_power: "Power words",
  ts_score_seo: "SEO",
  ts_empty_title: "Nhập ý tưởng để bắt đầu",
  ts_empty_desc: "AI sẽ tạo 12 title theo công thức proven cho kênh trading",
  ts_selected_title: "Title đã chọn",
  ts_goto_thumbnail: "Tạo thumbnail →",
  ts_char_count: (n: number) => `${n} ký tự`,

  // Step labels (8 steps, grouped into 4 phases for progress bar)
  step_context: "Bối cảnh",
  step_hook: "Thu hút",
  step_visual: "Hình ảnh",
  step_layout: "Bố cục",
  step_character: "Nhân vật",
  step_text: "Chữ",
  step_colors: "Màu sắc",
  step_style: "Phong cách",

  // Step 1 — Core Information
  s1_title: "Bối cảnh & Đối tượng",
  s1_topic: "Chủ đề video",
  s1_topic_ph: "VD: Price Action, Quản lý vốn, Trader lifestyle...",
  s1_video_title: "Tiêu đề video",
  s1_video_title_ph: "VD: Tôi đã mất 500 triệu vì sai lầm này...",
  s1_audience: "Đối tượng",
  s1_aud_newbie: "Mới bắt đầu",
  s1_aud_intermediate: "Có kinh nghiệm",
  s1_aud_advanced: "Chuyên gia",
  s1_aud_general: "Tất cả",
  s1_pain: "Nỗi đau",
  s1_pain_ph: "VD: Cháy tài khoản, không biết quản lý rủi ro...",
  s1_ai_suggest: "AI gợi ý tự động",

  // Step 2 — Desire Loop
  s2_title: "Chiến lược câu kéo",
  s2_problem: "Vấn đề hiện tại",
  s2_problem_ph: "VD: Giao dịch theo cảm xúc, thua liên tục...",
  s2_result: "Kết quả mong muốn",
  s2_result_ph: "VD: Có hệ thống giao dịch, lợi nhuận ổn định...",
  s2_trigger: "Cảm xúc kích hoạt",
  s2_shock: "Sốc",
  s2_shock_desc: "Phản ứng đỡ không nổi",
  s2_curiosity: "Tò mò",
  s2_curiosity_desc: "Phải xem ngay",
  s2_fomo: "FOMO",
  s2_fomo_desc: "Sợ bỏ lỡ",
  s2_inspiration: "Truyền cảm hứng",
  s2_inspiration_desc: "Mình cũng làm được",
  s2_controversy: "Gây tranh cãi",
  s2_controversy_desc: "Quan điểm nóng",
  s2_desire_loop: "Vòng lặp khao khát",

  // Step 3 — Visual Stun Gun
  s3_title: "Công thức hình ảnh",
  s3_elements: "Yếu tố thị giác",
  s3_high_contrast: "Tương phản cao",
  s3_big_face: "Khuôn mặt lớn",
  s3_curiosity_graph: "Biểu đồ gây tò mò",
  s3_giant_text: "Chữ cỡ khổng lồ",
  s3_red_arrows: "Mũi tên đỏ",
  s3_cinematic: "Điện ảnh",
  s3_collage: "Ghép ảnh",

  // Step 4 — Layout
  s4_title: "Bố cục thumbnail",
  s4_layout: "Bố cục",
  s4_symmetric: "Đối xứng",
  s4_symmetric_desc: "Cân bằng, hài hoà",
  s4_thirds: "Quy tắc 1/3",
  s4_thirds_desc: "Bố cục kinh điển",
  s4_split: "Chia đôi A/B",
  s4_split_desc: "So sánh trước & sau",

  // Step 5 — Character Library
  s5_title: "Nhân vật & Biểu cảm",
  s5_enable: "Sử dụng nhân vật",
  s5_upload: "Tải ảnh nhân vật",
  s5_upload_desc: "Kéo thả hoặc chọn ảnh khuôn mặt",
  s5_upload_btn: "Chọn ảnh",
  s5_change: "Đổi ảnh",
  s5_expression: "Biểu cảm mục tiêu",
  s5_original: "Giữ nguyên",
  s5_shocked: "Sốc",
  s5_happy: "Vui vẻ",
  s5_angry: "Tức giận",
  s5_sad: "Buồn",
  s5_confused: "Bối rối",
  s5_excited: "Phấn khích",

  // Step 6 — Text Overlay
  s6_title: "Chữ trên thumbnail",
  s6_text: "Nội dung chữ",
  s6_text_hint: "1-5 từ",
  s6_text_ph: "VD: CHÁY TÀI KHOẢN!",
  s6_style: "Kiểu chữ",
  s6_big_bold: "To & Đậm",
  s6_minimal: "Tối giản",
  s6_handwritten: "Viết tay",
  s6_neon: "Phát sáng",
  s6_goal: "Mục đích của chữ",
  s6_curiosity: "Gây tò mò",
  s6_urgency: "Tạo khẩn cấp",
  s6_value: "Thể hiện giá trị",
  s6_controversy: "Gây tranh cãi",
  s6_emotion: "Khơi cảm xúc",

  // Step 7 — Colors & Contrast
  s7_title: "Màu sắc & Tương phản",
  s7_primary: "Màu chủ đạo",
  s7_drop_shadow: "Đổ bóng chữ",
  s7_drop_shadow_desc: "Chữ nổi bật hơn trên nền",
  s7_high_contrast: "Tương phản cao",
  s7_high_contrast_desc: "Tăng độ tương phản tổng thể",

  // Step 8 — Visual Style
  s8_title: "Phong cách hình ảnh",
  s8_style: "Chọn phong cách",
  s8_youtube_viral: "YouTube Viral",
  s8_youtube_viral_desc: "Rực rỡ, bắt mắt, CTR cao",
  s8_cinematic: "Điện ảnh",
  s8_cinematic_desc: "Góc quay phim, ánh sáng đẹp",
  s8_minimalist: "Tối giản",
  s8_minimalist_desc: "Ít chi tiết, tập trung nội dung",
  s8_retro: "Retro",
  s8_retro_desc: "Phong cách hoài cổ, vintage",
  s8_dark_moody: "Tối & Huyền bí",
  s8_dark_moody_desc: "Tông tối, bí ẩn, cuốn hút",
  s8_colorful_pop: "Rực rỡ",
  s8_colorful_pop_desc: "Màu nổi bật, vui tươi",
  s8_professional: "Chuyên nghiệp",
  s8_professional_desc: "Sạch sẽ, đáng tin cậy",

  // Style Library
  sl_title: "Thư viện phong cách",
  sl_desc: "Upload thumbnail mẫu từ kênh yêu thích, AI sẽ học phong cách",
  sl_add: "Thêm phong cách",
  sl_channel: "Tên kênh",
  sl_channel_ph: "VD: Hannah Forex",
  sl_upload: "Upload thumbnail mẫu",
  sl_upload_desc: "2-5 ảnh thumbnail từ kênh này",
  sl_upload_btn: "Chọn ảnh",
  sl_analyzing: "AI đang phân tích...",
  sl_analyze: "Phân tích phong cách",
  sl_delete: "Xoá",
  sl_selected: "Đang dùng",
  sl_select: "Chọn",
  sl_none: "Không dùng style mẫu",
  sl_images: (n: number) => `${n} ảnh mẫu`,

  // Studio Mode
  mode_full: "Đầy đủ",
  mode_full_desc: "8 bước tuỳ chỉnh chi tiết",
  mode_quick: "Tạo nhanh",
  mode_quick_desc: "Chỉ điền nội dung, AI lo phần còn lại",

  // Navigation
  nav_back: "Quay lại",
  nav_next: "Tiếp tục",
  nav_preview_prompt: "Xem Prompt",
  nav_generate: "Tạo thumbnail",
  nav_generating: "Đang tạo...",
  nav_quick: "Tạo nhanh — Bỏ qua bước, để AI lo",

  // Edit
  edit_title: "Chỉnh sửa",
  edit_desc: "Chọn thumbnail rồi chỉnh sửa bằng AI",
  edit_select: "Chọn thumbnail",
  edit_empty: "Chưa có thumbnail nào. Hãy tạo ở Thumbnail trước.",
  edit_instruction: "Hướng dẫn chỉnh sửa",
  edit_instruction_ph: "Mô tả thay đổi bạn muốn...",
  edit_quick: "Chỉnh nhanh",
  edit_q1: "Thêm viền neon đỏ",
  edit_q2: "Nền tối hơn",
  edit_q3: "Thêm mũi tên đỏ",
  edit_q4: "Chữ to hơn + đổ bóng",
  edit_q5: "Màu phim điện ảnh",
  edit_q6: "Biểu cảm sốc",
  edit_apply: "Áp dụng chỉnh sửa",
  edit_applying: "Đang áp dụng...",

  // Gallery
  gal_title: "Bộ sưu tập",
  gal_count: (n: number) => `${n} thumbnail đã tạo`,
  gal_empty_title: "Chưa có thumbnail nào",
  gal_empty_desc: "Tạo thumbnail đầu tiên ở Thumbnail Studio",
  gal_open_studio: "Mở Thumbnail",

  // Watermark
  wm_title: "Watermark",
  wm_desc: "Bảo vệ thumbnail với watermark thông minh",
  wm_preset: "Mẫu có sẵn",
  wm_preset_branding: "Thương hiệu",
  wm_preset_branding_desc: "Logo & tên kênh",
  wm_preset_anti_repost: "Chống repost",
  wm_preset_anti_repost_desc: "Chìm + lặp lại",
  wm_preset_educational: "Giáo dục",
  wm_preset_educational_desc: "Tinh tế, góc dưới",
  wm_type: "Loại watermark",
  wm_type_subtle: "Chữ mờ",
  wm_type_bold: "Chữ đậm",
  wm_type_image: "Hình ảnh",
  wm_text: "Nội dung watermark",
  wm_text_ph: "@MSSpace",
  wm_upload: "Tải logo",
  wm_position: "Vị trí",
  wm_pos_tl: "Trên trái",
  wm_pos_tr: "Trên phải",
  wm_pos_bl: "Dưới trái",
  wm_pos_br: "Dưới phải",
  wm_pos_center: "Chính giữa",
  wm_pos_auto: "Tự động",
  wm_color_mode: "Chế độ màu",
  wm_color_adaptive: "Tự thích ứng",
  wm_color_light: "Sáng",
  wm_color_dark: "Tối",
  wm_platform: "Nền tảng",
  wm_plat_youtube: "YouTube",
  wm_plat_instagram: "Instagram",
  wm_plat_tiktok: "TikTok",
  wm_plat_general: "Chung",
  wm_opacity: "Độ mờ",
  wm_text_size: "Cỡ chữ",
  wm_rotation: "Xoay",
  wm_avoid_faces: "Tránh khuôn mặt",
  wm_avoid_faces_desc: "AI sẽ không đặt watermark lên mặt người",
  wm_repeat: "Lặp lại",
  wm_repeat_desc: "Tạo mẫu watermark lặp lại toàn ảnh",
  wm_preview: "Xem trước",
  wm_apply: "Áp dụng watermark",

  // Workspace
  ws_title: "Không gian làm việc",
  ws_size: "1280 × 720 — Thumbnail YouTube",
  ws_download: "Tải về",
  ws_creating: "Đang tạo thumbnail...",
  ws_creating_desc: "Chờ khoảng 10-30 giây nhé",
  ws_empty_title: "Chưa có thumbnail",
  ws_empty_desc:
    "Điền thông tin trong Studio rồi bấm Tạo ảnh để AI tạo thumbnail đầu tiên cho bạn",
  ws_meta_title: "Thông tin nội dung",
  ws_meta_generate: "Tạo tự động",
  ws_meta_label_title: "Tiêu đề",
  ws_meta_label_desc: "Mô tả",
  ws_meta_label_tags: "Từ khoá",
  ws_meta_empty: "Tạo tự động tiêu đề, mô tả và từ khoá cho video",
  ws_prompt_title: "AI Prompt",
  ws_prompt_copy: "Sao chép",
  ws_social: "Liên kết cộng đồng",
  ws_social_skool: "Skool",
  ws_social_skool_ph: "Link nhóm Skool...",
  ws_social_facebook: "Facebook",
  ws_social_facebook_ph: "Link nhóm Facebook...",
} as const;
